platform :ios, '9.0'

def shared_pods
  
  # Rx
  pod 'RxSwift', '~> 4.0'
  pod 'RxCocoa', '~> 4.0'
  pod 'RxAlamofire', '~> 4.0'
  
  # Map
  pod 'GoogleMaps'
  
  # UI Helpers
  pod 'SnapKit'
end

target 'Glovo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Glovo
  shared_pods

  target 'GlovoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'GlovoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
